services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pruebatt-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TuClaveFuerte123!"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost",
             "-U", "sa", "-P", "TuClaveFuerte123!", "-Q", "SELECT 1",
             "-No", "-C"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  servicio-autenticacion:
    build:
      context: ./backend/ServicioAutenticacion
    container_name: pruebatt-autenticacion
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AutenticacionDb=Server=sqlserver,1433;Database=AutenticacionDb;User Id=sa;Password=TuClaveFuerte123!;TrustServerCertificate=True
      - Jwt__Clave=CAMBIA_ESTA_CLAVE_POR_UNA_SECRETA_DE_AL_MENOS_32_CARACTERES
      - Jwt__Emisor=ServicioAutenticacion
      - Jwt__Audiencia=PruebaTT
    depends_on:
      sqlserver:
        condition: service_healthy

  servicio-clientes-pedidos:
    build:
      context: ./backend/ServicioClientesPedidos
    container_name: pruebatt-clientes-pedidos
    ports:
      - "8080:80"
    environment:
      - DB_SERVIDOR=sqlserver
      - DB_NOMBRE=ClientesPedidosDb
      - DB_USUARIO=sa
      - DB_CLAVE=TuClaveFuerte123!
      - JWT_CLAVE=CAMBIA_ESTA_CLAVE_POR_UNA_SECRETA_DE_AL_MENOS_32_CARACTERES
    depends_on:
      sqlserver:
        condition: service_healthy

  servicio-estadisticas:
    build:
      context: ./backend/ServicioEstadisticas
    container_name: pruebatt-estadisticas
    ports:
      - "8001:8000"
    environment:
      - DB_SERVIDOR=sqlserver,1433
      - DB_NOMBRE=ClientesPedidosDb
      - DB_USUARIO=sa
      - DB_CLAVE=TuClaveFuerte123!
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqldata:
